version: "3.9"  # optional since v1.27.0
services:
  jenkins:
    container_name: jenkins
    image: moody1511/jenkinsdocker:1.0
    ports:
      - "8080:8080"
    volumes:
      - $PWD/jenkins_home:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - net
networks:
    net:

